config/routes.rb
Rails.application.routes.draw do
  resources :fish_tweets
  get 'rare_fish_map/index'
  resources :rare_fishes
  devise_for :users
  get 'portfolio/index'
  get 'static_pages/home'
  resources :articles
  get 'welcome/index'
  root 'rare_fish_map#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/fish_tweet.rb
class FishTweet < ApplicationRecord
  belongs_to :user
end

app/models/rare_fish.rb
class RareFish < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

protected

def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  devise_parameter_sanitizer.permit(:account_update, keys: [:name])
end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:content, :point)
    end
end

app/controllers/fish_tweets_controller.rb
class FishTweetsController < ApplicationController
  protect_from_forgery
  before_action :authenticate_user!, only: [:new, :create, :update, :destroy]
  before_action :set_fish_tweet, only: %i[ show edit update destroy ]

  
  # GET /fish_tweets or /fish_tweets.json
  def index
    @fish_tweets = FishTweet.all
  end

  # GET /fish_tweets/1 or /fish_tweets/1.json
  def show
  end

  # GET /fish_tweets/new
  def new
    @fish_tweet = FishTweet.new
    
  end

  # GET /fish_tweets/1/edit
  def edit
  end

  # POST /fish_tweets or /fish_tweets.json
  def create
    @fish_tweet = FishTweet.new(fish_tweet_params)
    @fish_tweet.user_id = current_user.id

    respond_to do |format|
      if @fish_tweet.save
        format.html { redirect_to @fish_tweet, notice: "Fish tweet was successfully created." }
        format.json { render :show, status: :created, location: @fish_tweet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @fish_tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fish_tweets/1 or /fish_tweets/1.json
  def update
      if @fish_tweet.user_id == current_user.id
        respond_to do |format|
          if @fish_tweet.update(fish_tweet_params)
            format.html { redirect_to @fish_tweet, notice: '内容を変更しました。' }
            format.json { render :show, status: :ok, location: @fish_tweet }
          else
            format.html { render :edit }
            format.json { render json: @fish_tweet.errors, status: :unprocessable_entity }
          end
        end
      else
          redirect_to @fish_tweet, notice: "権限がありません。"
      end
  end
  

  # DELETE /fish_tweets/1 or /fish_tweets/1.json
  def destroy
    if @fish_tweet.user_id == current_user.id
        @fish_tweet.destroy
        msg = "削除しました。"
      else
        msg = "権限がありません。"
      end
    respond_to do |format|
      format.html { redirect_to fish_tweets_url, notice:msg }
      format.json { head :no_content }
    end
  end

  public
    # Use callbacks to share common setup or constraints between actions.
    def set_fish_tweet
      @fish_tweet = FishTweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def fish_tweet_params
      params.require(:fish_tweet).permit(:user_id, :image, :content, :like)
    end
end

app/controllers/portfolio_controller.rb
class PortfolioController < ApplicationController
  layout "portfolio_layouts"

  def index
  end
end

app/controllers/rare_fish_map_controller.rb
class RareFishMapController < ApplicationController
  before_action :set_rare_fish, only: %i[ show edit update destroy ]
  def index
    @rare_fishes = RareFish.all
    @fish_tweets = FishTweet.all
  end
 
end

app/controllers/rare_fishes_controller.rb
class RareFishesController < ApplicationController
  before_action :set_rare_fish, only: %i[ show edit update destroy ]

  # GET /rare_fishes or /rare_fishes.json
  def index
    @rare_fishes = RareFish.all
  end


  # GET /rare_fishes/1 or /rare_fishes/1.json
  def show
  end

  # GET /rare_fishes/new
  def new
    @rare_fish = RareFish.new
  end

  # GET /rare_fishes/1/edit
  def edit
  end

  # POST /rare_fishes or /rare_fishes.json
  def create
    @rare_fish = RareFish.new(rare_fish_params)

    respond_to do |format|
      if @rare_fish.save
        format.html { redirect_to @rare_fish, notice: "Rare fish was successfully created." }
        format.json { render :show, status: :created, location: @rare_fish }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @rare_fish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rare_fishes/1 or /rare_fishes/1.json
  def update
    respond_to do |format|
      if @rare_fish.update(rare_fish_params)
        format.html { redirect_to @rare_fish, notice: "Rare fish was successfully updated." }
        format.json { render :show, status: :ok, location: @rare_fish }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @rare_fish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rare_fishes/1 or /rare_fishes/1.json
  def destroy
    @rare_fish.destroy
    respond_to do |format|
      format.html { redirect_to rare_fishes_url, notice: "Rare fish was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  public
    # Use callbacks to share common setup or constraints between actions.
    def set_rare_fish
      @rare_fish = RareFish.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def rare_fish_params
      params.require(:rare_fish).permit(:fish_id, :user, :title, :content, :image, :adless, :like)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/fish_tweets_helper.rb
module FishTweetsHelper
end

app/helpers/portfolio_helper.rb
module PortfolioHelper
end

app/helpers/rare_fish_map_helper.rb
module RareFishMapHelper
end

app/helpers/rare_fishes_helper.rb
module RareFishesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="field">
    <%= form.label :point %>
    <%= form.number_field :point %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
   <div class="container">
        <div class="starter-template">

<p id="notice"><%= notice %></p>

<h1>Articles</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Point</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <% @articles.each do |article| %>
      <tr>
        <td><%= article.content %></td>
        <td><%= article.point %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= button_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path, class: 'btn btn-primary' %>

</div>
</div>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @article.content %>
</p>

<p>
  <strong>Point:</strong>
  <%= @article.point %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/fish_tweets/edit.html.erb
<h1>Editing Fish Tweet</h1>

<%= render 'form', fish_tweet: @fish_tweet %>

<%= link_to 'Show', @fish_tweet %> |
<%= link_to 'Back', fish_tweets_path %>

app/views/fish_tweets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fish Tweets</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Image</th>
      <th>Content</th>
      <th>Like</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fish_tweets.each do |fish_tweet| %>
      <tr>
        <td><%= fish_tweet.user.name %></td>
        <td><%= fish_tweet.image %></td>
        <td><%= fish_tweet.content %></td>
        <td><%= fish_tweet.like %></td>
        <td><%= link_to 'Show', fish_tweet %></td>
        <% if user_signed_in? && fish_tweet.user_id == current_user.id %>

        
        <td><%= link_to 'Edit', edit_fish_tweet_path(fish_tweet) %></td>
        <td><%= button_to 'Destroy', fish_tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fish Tweet', new_fish_tweet_path %>

app/views/fish_tweets/new.html.erb
<h1>New Fish Tweet</h1>

<%= render 'form', fish_tweet: @fish_tweet %>

<%= link_to 'Back', fish_tweets_path %>

app/views/fish_tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @fish_tweet.user_id %>
</p>

<p>
  <strong>Image:</strong>
  <%= @fish_tweet.image %>
</p>

<p>
  <strong>Content:</strong>
  <%= @fish_tweet.content %>
</p>

<p>
  <strong>Like:</strong>
  <%= @fish_tweet.like %>
</p>

<%= link_to 'Edit', edit_fish_tweet_path(@fish_tweet) %> |
<%= link_to 'Back', fish_tweets_path %>

app/views/portfolio/index.html.erb
<html>
  <head>

<div class="container">
        <div class="starter-template">
            <h1>Welcome My Portfolio!</h1>
            <p class="lead">駆け出しエンジニアのポートフォリオ公開中</p>
            <p>-</p>
            
            <div class="row text-center">

                <div class="col-sm-4">
                    <h3 class="color-handshake"><i class="far fa-handshake fa-3x"></i></span><br>会話・説明力</h3>
                    <p>コールセンターの勤務経験を活かした、<br>誰にでも理解しやすい、わかりやすい説明を心がけています。</p>
                </div>
                <div class="col-sm-4">
                    <h3 class="color-wrench"><i class="fas fa-wrench fa-3x"></i></span><br>アプリ制作</h3>
                    <p>フレームワーク　：　Ruby on Rails<br>エディタ　：　VScode<br>Githubからherokuへの自動デプロイ</p>
                </div>
                <div class="col-sm-4">
                    <h3 class="color-run"><i class="fas fa-running fa-3x"></i></i></span><br>行動力</h3>
                    <p>独学でプログラミングを学習<br>常に自走能力の向上を目指しています。</p>
                </div>
            </div>
            <p>-</p>

            <h2 id="works">制作したアプリ</h2><br>
            <h4>↓↓クリック or タップ↓↓</h4>
                        <div class="row">
                <div class="col-sm-6">
                    <h3><%= link_to 'Rare Fish Eats MAP',rare_fish_map_index_path %></h3>
                    <p>珍しくてあまり知られていない、美味しい魚の情報を掲載。</p>
                    <p>そして、その珍しい魚を実際に食べられるお店のMAPが表示されるWEBアプリ。<br></p>
                    <p>記事に対するコメント・いいね・ユーザー認証機能を搭載。</p>
                </div>
                <div class="col-sm-6">
                    <img src="https://user-images.strikinglycdn.com/res/hrscywv4p/image/upload/c_limit,fl_lossy,h_9000,w_1200,f_auto,q_auto/1714939/123535_728148.jpeg" class="img-fluid" alt="Responsive image">
                </div>
            </div>
            <hr>
            <h2 id="skills">Skills</h2>
            <p>開発環境<br>
              Ruby 2. 7. 2<br>
              Rails 5. 2. 4</p>
            
            <i class="fab fa-twitter-square fa-5x twitter-blue"></i>
            <i class="fab fa-line fa-5x line-green"></i>
            <i class="fab fa-facebook-square fa-5x facebook-blue"></i>
            <i class="fab fa-amazon fa-5x amazon-black"></i>
            <i class="fab fa-youtube fa-5x youtube-red"></i>
            <i class="fab fa-docker fa-5x docker-blue"></i>
            <i class="fab fa-github fa-5x github-black"></i>

            <div class="row starter-template">
            <a class="btn btn-primary" href="#">Topに戻る</a>
        </div>
    </div>

  </head>



<div class="container">
  <div class="jumbotron m-3">
    <h1 class="display-4">Hello, Bootstrap!</h1>
    <hr class="my-4">
    <p>This is the template of Ruby on Rails using Bootstrap.</p>
    <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#exampleModal">
      <i class="far fa-window-maximize"></i>
      Click here
    </button>
  </div>
  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">モデル タイトル</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          Hello!
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
</div>

</html>

app/views/rare_fish_map/index.html.erb
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to "Settings", edit_user_registration_path %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete %>
<% end %>
<h1>RareFishMap#index</h1>
<p>Find me in app/views/rare_fish_map/index.html.erb</p>

<div class="container">
  <div class="starter-template">
    <div class="row text-left">
      <div class="col-sm-6">
        デバッグ用の掲示板<p id="notice"><%= notice %></p>

        <h1>Rare Fishes</h1>
        
        <table>
          <thead>
            <tr>
              <th>Fish</th>
              <th>User</th>
              <th>Title</th>
              <th>Content</th>
              <th>Image</th>
              <th>Adless</th>
              <th>Like</th>
              <th colspan="3"></th>
            </tr>
          </thead>
        
          <tbody>
            <% @rare_fishes.each do |rare_fish| %>
              <tr>
                <td><%= rare_fish.fish_id %></td>
                <td><%= rare_fish.user %></td>
                <td><%= rare_fish.title %></td>
                <td><%= rare_fish.content %></td>
                <td><%= rare_fish.image %></td>
                <td><%= rare_fish.adless %></td>
                <td><%= rare_fish.like %></td>
                <td><%= link_to 'Show', rare_fish %></td>
                <td><%= link_to 'Edit', edit_rare_fish_path(rare_fish) %></td>
                <td><%= button_to 'Destroy', rare_fish, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        
        <br>
        
        <%= link_to 'New Rare Fish', new_rare_fish_path %>
        
      </div>
      <div class="col-sm-6">
        ここにコメントが記述される
        <p id="notice"><%= notice %></p>

<h1>Fish Tweets</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Image</th>
      <th>Content</th>
      <th>Like</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fish_tweets.each do |fish_tweet| %>
      <tr>
        <td><%= fish_tweet.user.name %></td>
        <td><%= fish_tweet.image %></td>
        <td><%= fish_tweet.content %></td>
        <td><%= fish_tweet.like %></td>
        <td><%= link_to 'Show', fish_tweet %></td>
        <% if user_signed_in? && fish_tweet.user_id == current_user.id %>

        
        <td><%= link_to 'Edit', edit_fish_tweet_path(fish_tweet) %></td>
        <td><%= button_to 'Destroy', fish_tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fish Tweet', new_fish_tweet_path %>
        
      </div>
    </div>
  </div>
</div>

<!--コンテナを分ける--><br>

<div class="container">
  <div class="starter-template">
    <div class="row text-left">
      <div class="col-sm-6">
        ここに詳細が記述される<p id="notice"><%= notice %></p>

        <h1>Rare Fishes</h1>
        
        <table>
          <thead>
            <tr>
              <th>Fish</th>
              <th>User</th>
              <th>Title</th>
              <th>Content</th>
              <th>Image</th>
              <th>Adless</th>
              <th>Like</th>
              <th colspan="3"></th>
            </tr>
          </thead>
        
          <tbody>
            <% @rare_fishes.each do |rare_fish| %>
              <tr>
                <td><%= rare_fish.fish_id[1] %></td>
                
                <td><%= rare_fish.user %></td>
                <td><%= rare_fish.title %></td>
                <td><%= rare_fish.content %></td>
                <td><%= rare_fish.image %></td>
                <td><%= rare_fish.adless %></td>
                <td><%= rare_fish.like %></td>
                <td><%= link_to '詳細', rare_fish, class: 'btn btn-success' %></td>
              </tr>
            <% end %>

          
          </tbody>
        </table>
        
        <br>
        
        <%= link_to 'New Rare Fish', new_rare_fish_path %>
        
      </div>
      <div class="col-sm-6">
        デバッグ用のテストエリア<br>
        <% player = ["test","test2","test3"] %>
        <% player2 = ["test","Nice Here!!","test3"] %>
        <% player3 = ["test","test2","test3"] %>
        <% team = [player,player2,player3] %>
        <% price = 2500 * 1.05 %>
        <% array = [[10,20],[30,40]] %>
        <% array.each do |a| %>
        <%= p a %>
        <p>ーーーー</p>
        
        <p>ーーーー</p>
        <% end %>
<p>
スタートポイント：<%= team %>：エンドポイント。<br>
スタートポイント：<%= @rare_fishes %>：エンドポイント。
</p>
      </div>
    </div>
  </div>
</div>

<!--さらにコンテナを分ける--><br>
<% x = 0 %>

<% @rare_fishes.each do |rare_fish| %>
<tr>
  <div class="container">
    <div class="starter-template">
      <div class="row text-left">
        <div class="col-sm-6">
  <td><%= rare_fish.fish_id %></td>
  
  <td><%= rare_fish.user %></td>
  <td><%= rare_fish.title %></td>
  <td><%= rare_fish.content %></td>
  <td><%= rare_fish.image %></td>
  <td><%= rare_fish.adless %></td>
  <td><%= rare_fish.like %></td>
  <td><%= link_to 'Show', rare_fish %></td>
</tr></div>
<div class="col-sm-6">
ここにコメントが記載される
  <p id="notice"><%= notice %></p>

  <h1>Fish Tweets</h1>
  
  <table>
    <thead>
      <tr>
        <th><%= x %></th>
        <th>User</th>
        <th>Image</th>
        <th>Content</th>
        <th>Like</th>
        <th colspan="3"></th>
      </tr>
    </thead>
  
    <tbody>
      <% @fish_tweets.each do |fish_tweet| %>
        <tr>
          <% if x==0 && fish_tweet.image == "ケイジ" %>
          <td><%= fish_tweet.user.name %></td>
          <td><%= fish_tweet.image %></td>
          <td><%= fish_tweet.content %></td>
          <td><%= fish_tweet.like %></td>
          <td><%= link_to 'Show', fish_tweet %></td>
          <% if user_signed_in? && fish_tweet.user_id == current_user.id %>
  
          
          <td><%= link_to 'Edit', edit_fish_tweet_path(fish_tweet) %></td>
          <td><%= button_to 'Destroy', fish_tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
        <% elsif x==1 && fish_tweet.image == "クエ" %>
        <td><%= fish_tweet.user.name %></td>
          <td><%= fish_tweet.image %></td>
          <td><%= fish_tweet.content %></td>
          <td><%= fish_tweet.like %></td>
          <td><%= link_to 'Show', fish_tweet %></td>
          <% if user_signed_in? && fish_tweet.user_id == current_user.id %>
  
          
          <td><%= link_to 'Edit', edit_fish_tweet_path(fish_tweet) %></td>
          <td><%= button_to 'Destroy', fish_tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
        <% elsif x==2 %>
        エルス２
        <% elsif x==3 %>
        エルス３
        <% elsif x==4 %>
        エルス４
        <% elsif x==5 %>
        エルス５
        <% elsif x==6 %>
        エルス６
        <% else %>
        
        <% end %>
      <% end %>
    </tbody>
  </table>
  
  <br>
  
  <%= link_to 'New Fish Tweet', new_fish_tweet_path %>
</div>
</div></div></div><br>
<%= x = x+1 %>
<% end %>

app/views/rare_fishes/edit.html.erb
<h1>Editing Rare Fish</h1>

<%= render 'form', rare_fish: @rare_fish %>

<%= link_to 'Show', @rare_fish %> |
<%= link_to 'Back', rare_fishes_path %>

app/views/rare_fishes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rare Fishes</h1>

<table>
  <thead>
    <tr>
      <th>Fish</th>
      <th>User</th>
      <th>Title</th>
      <th>Content</th>
      <th>Image</th>
      <th>Adless</th>
      <th>Like</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rare_fishes.each do |rare_fish| %>
      <tr>
        <td><%= rare_fish.fish_id %></td>
        <td><%= rare_fish.user %></td>
        <td><%= rare_fish.title %></td>
        <td><%= rare_fish.content %></td>
        <td><%= rare_fish.image %></td>
        <td><%= rare_fish.adless %></td>
        <td><%= rare_fish.like %></td>
        <td><%= link_to 'Show', rare_fish %></td>
        <td><%= link_to 'Edit', edit_rare_fish_path(rare_fish) %></td>
        <td><%= link_to 'Destroy', rare_fish, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rare Fish', new_rare_fish_path %>

app/views/rare_fishes/new.html.erb
<h1>New Rare Fish</h1>

<%= render 'form', rare_fish: @rare_fish %>

<%= link_to 'Back', rare_fishes_path %>

app/views/rare_fishes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fish:</strong>
  <%= @rare_fish.fish_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @rare_fish.user %>
</p>

<p>
  <strong>Title:</strong>
  <%= @rare_fish.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @rare_fish.content %>
</p>

<p>
  <strong>Image:</strong>
  <%= @rare_fish.image %>
</p>

<p>
  <strong>Adless:</strong>
  <%= @rare_fish.adless %>
</p>

<p>
  <strong>Like:</strong>
  <%= @rare_fish.like %>
</p>

<%= link_to 'Edit', edit_rare_fish_path(@rare_fish) %> |
<%= link_to 'Back', rare_fishes_path %>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>
<h1>Sample App</h1>

app/views/welcome/index.html.erb
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to "Settings", edit_user_registration_path %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete %>
<% end %>


<h1>Welcome#index</h1>
<h1>Hello Heroku!</h1>
<h2>test h2</h2>
<p><%= Date.today %></p>
<p>Find me in app/views/welcome/index.html.erb</p>

<%= link_to '一行掲示板へ' ,articles_path , class: 'btn btn-primary'%>